### ISSUE TITLE
send Marty note to share on making plant tool non-uniform spherical

### ISSUE THREAD

**Issue by tokkentakker** [2016-RCAD-GA-Thesis/terminal#28]

**Comment by rhuberga** [comment]
Michael Curtiss has sent a detailed explanation of how to make an elipse.
http://www.mathwarehouse.com/ellipse/equation-of-ellipse.php

**Comment by tokkentakker** [comment]
Can you apply this?

I have down the two pins and string trick but did not fully understand the math.

On Nov 1, 2015, at 11:48 PM, rhuberga notifications@github.com wrote:

Michael Curtiss has sent a detailed explanation of how to make an elipse.
http://www.mathwarehouse.com/ellipse/equation-of-ellipse.php

**Comment by rhuberga** [comment]
Yeah, it's doable.
I can see where I went wrong based on that webpage.
Never took trig in school so I was just guessing on how to make the shape.
