### ISSUE TITLE
identify "key asset" for FALL

### ISSUE THREAD

**Issue by tokkentakker** [2016-RCAD-GA-Thesis/terminal#3]

**Comment by rhuberga** [comment]
I think my key asset might be the Neurons. There's a close-up shot of one near the beginning of the trailer, which includes a material effect, and possibly a blend shape.
(the current design is similar to this: https://youtu.be/rD3oxP2pToI?t=2m9s)
It also ties into the brain theme the best.
My other contender would be the 'vents' (volcanoes) but despite featuring heavily in the environment towards the end, I think they're more of a background element.

Your thoughts?

**Comment by tokkentakker** [comment]
if the neurons are closer to that organic architecture shared earlier this summer I could see that being a good contender for key asset.  resolved?
